# Website settings
url: "https://iyyel.io"

# Internal nav
nav:
  main:
    writing: "/writing"
    resume: "/resume"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"

# Bio settings
name: "Daniel Larsen"
description: "The home page of Daniel Larsen, a passionate full-stack developer thriving to solve complex problems through scalable and maintainble software."
thumbnail_path: "author/author_grayscale.jpg"
website_repo_url: "https://github.com/iyyel/iyyel.io"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/daniellrsn/"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/daniellrsn/"
    label: "Facebook"
    icon: "facebook-square"
  github:
    url: "https://github.com/iyyel/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:i@iyyel.io"
    label: "Email"
    value: "i@iyyel.io"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'Europe/Copenhagen'
repository: iyyel/iyyel.io

# Plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate