# SEO settings
title: InAbsentia
site_name: "ALL THINGS *NIX"
title_description: "*nix site about software engineering and other wonderful niche things"
description: "ALL THINGS *NIX is a website that documents the journey of aspiring software engineer, InAbsentia. The site is about software engineering with a focus on 
*nix-like systems in the aspects of usage and software development."
keywords: "ricing, linux, nix, *nix, unix, unix-like, bsd, arch, gentoo, funtoo, ubuntu, open-source, gpl, mit, git, code, coding, programming, software, engineer, 
           engineering, development, developer, programmer, computer, science, security, network, networking, personal, website, project"

url: https://inabsentia.io
baseurl: null

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: src
destination: html

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "InAbsentia"
  job      : " ..buffer overflow.."
  bio      : "ricer // *nix enthusiast // software engineer"
  thumb    : /images/author.jpg
  email    : absentia@inabsentia.io
  url      : https://inabsentia.io
  github   : https://github.com/inabsencia

# social settings
og_locale: "en_US"

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : projects
    title: projects
  - slug : resume
    title: resume
  - slug : contact
    title: contact
  - slug : feed
    title: feed

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
