name: iyyel-io
version: 1.5.0.0
github: "iyyel"
license: MIT
author: "Daniel Larsen"
maintainer: "i@iyyel.io"
copyright: "2020 Daniel Larsen"

dependencies:
  - base >= 4.7 && < 5
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  site:
    main: Site.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hakyll
